### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by Skywalker13** [Skywalker13/atom-wannabe#5]
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [atom-wannabe](https://github.com/Skywalker13/atom-wannabe) package 0.3.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /opt/atom/resources/app.asar/src/decoration-manager.js:204

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/app.asar/src/decoration-manager.js:194:17)
    at TextEditor.module.exports.TextEditor.decorateMarker (/app.asar/src/text-editor.js:1732:37)
    at FrameMark.show (/home/schroeterm/devel/atom-wannabe/lib/frame-mark.js:219:36)
    at FrameMark.setVisibility (/home/schroeterm/devel/atom-wannabe/lib/frame-mark.js:226:12)
    at _event._editor.getElement.onDidChangeScrollTop (/home/schroeterm/devel/atom-wannabe/lib/frame-mark.js:146:12)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at /app.asar/src/text-editor-element.js:105:46
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/app.asar/src/text-editor-presenter.js:944:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.commitPendingScrollTopPosition (/app.asar/src/text-editor-presenter.js:1968:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/app.asar/src/text-editor-presenter.js:118:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/app.asar/src/text-editor-component.js:264:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:196:12)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
     -2:22.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-theme.theme-one-dark-ui)
     -2:09.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:00.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-theme.theme-one-dark-ui)
     -0:19.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
atom-wannabe 0.3.0 
autocomplete-clang 0.11.3 
autocomplete-emojis 2.5.0 
busy-signal 1.4.1 
color-picker 2.2.5 
console-panel 0.2.1 
docblockr 0.9.4 
dracula-theme 2.0.3 
editorconfig 2.2.2 
emmet 2.4.3 
exception-reporting 0.41.4 
file-icons 2.1.4 
gdb-debug 0.0.3 
git-blame 1.0.1 
git-plus 7.8.0 
git-time-machine 1.5.9 
go-debug 1.3.1 
go-plus 5.5.1 
go-signature-statusbar 1.2.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hix 0.1.0 
hyperclick 0.0.40 
intentions 1.1.2 
jsformat 0.9.3 
language-batch 0.4.0 
language-cmake 0.3.0 
language-debian 0.2.1 
language-diff 0.7.0 
language-nsis 5.20.2 
linter 2.1.4 
linter-clang 4.1.1 
linter-cpplint 2.0.1 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-golinter 1.2.2 
linter-gotype 0.1.0 
linter-govet 0.1.5 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-ui-default 1.2.4 
markdown-deluxe 1.0.0 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
metrics 1.2.3 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
node-debugger 1.10.1 
pigments 0.39.1 
prettier-atom-space-parenthesis 0.30.101 
pretty-json 1.6.3 
react 0.16.2 
rest-client 1.3.1 
sloc 1.1.0 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
todo-show 1.11.0 
xml-formatter 0.10.0 
```

**Comment by Skywalker13** [comment]
Fixed by 05324871b67bdc8ac6f8cd80f4f772cab42f11c2
