### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Skywalker13** [Skywalker13/atom-wannabe#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [atom-wannabe](https://github.com/Skywalker13/atom-wannabe) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /home/schroeterm/devel/atom-wannabe/lib/test-mark.js:45

TypeError: Cannot read property '0' of null
    at new TestMark (/home/schroeterm/devel/atom-wannabe/lib/test-mark.js:45:37)
    at MarkRegistry.createTestMark (/home/schroeterm/devel/atom-wannabe/lib/mark-registry.js:91:20)
    at Runner.<anonymous> (/home/schroeterm/devel/atom-wannabe/lib/atom-wannabe.js:36:26)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at _extracted.tests.some.test (/home/schroeterm/devel/wannabe.js/lib/runner.js:116:16)
    at Array.some (native)
    at ChildProcess._mocha.on.runner (/home/schroeterm/devel/wannabe.js/lib/runner.js:112:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### Commands

```
     -1:04.6.0 core:select-all (input.hidden-input)
     -1:04.3.0 core:copy (input.hidden-input)
     -1:03.3.0 intentions:highlight (input.hidden-input)
     -1:03.0 core:select-all (input.hidden-input)
     -1:02.7.0 core:paste (input.hidden-input)
     -1:02.4.0 core:save (input.hidden-input)
     -0:59.9.0 intentions:highlight (input.hidden-input)
     -0:59.6.0 core:save (input.hidden-input)
     -0:31.1.0 intentions:highlight (input.hidden-input)
     -0:30.8.0 core:select-all (input.hidden-input)
     -0:30.5.0 core:copy (input.hidden-input)
     -0:29.1.0 intentions:highlight (input.hidden-input)
     -0:28.8.0 core:select-all (input.hidden-input)
     -0:28.5.0 core:paste (input.hidden-input)
     -0:27.2.0 intentions:highlight (input.hidden-input)
     -0:27 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
atom-wannabe 0.4.1 
autocomplete-clang 0.11.3 
autocomplete-emojis 2.5.0 
busy-signal 1.4.1 
color-picker 2.2.5 
console-panel 0.2.1 
docblockr 0.9.4 
dracula-theme 2.0.3 
editorconfig 2.2.2 
emmet 2.4.3 
environment 1.3.1 
exception-reporting 0.41.4 
file-icons 2.1.5 
git-blame 1.0.1 
git-plus 7.8.0 
git-time-machine 1.5.9 
go-debug 1.3.1 
go-plus 5.5.2 
go-signature-statusbar 1.2.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hix 0.1.0 
hyperclick 0.0.40 
intentions 1.1.2 
jsformat 0.9.3 
language-batch 0.4.0 
language-cmake 0.3.0 
language-debian 0.2.1 
language-diff 0.7.0 
language-nsis 5.20.2 
linter 2.1.4 
linter-clang 4.1.1 
linter-cpplint 2.0.1 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-golinter 1.2.2 
linter-gotype 0.1.0 
linter-govet 0.1.5 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-markdown 4.0.1 
linter-ui-default 1.2.4 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
metrics 1.2.4 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
prettier-atom-space-parenthesis 0.30.102 
pretty-json 1.6.3 
react 0.16.2 
rest-client 1.3.1 
sloc 1.1.0 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
todo-show 1.11.0 
xatom-debug 1.6.7 
xatom-debug-chrome 0.7.2 
xatom-debug-nodejs 0.9.1 
xml-formatter 0.10.0 
```

**Comment by Skywalker13** [comment]
Fixed by d3918cb845e6a1403278914fe53d95d2d659ecc4
