### ISSUE TITLE
Failed to load the atom-wannabe package

### ISSUE THREAD

**Issue by SBrinkworth** [Skywalker13/atom-wannabe#7]
[Enter steps to reproduce:]

1. I open atom and this error pops up

**Atom**: 1.45.0-beta0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-wannabe](https://github.com/Skywalker13/atom-wannabe) package 0.4.1

### Stack Trace

Failed to load the atom-wannabe package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-wannabe/node_modules/wannabe/lib/runner.js:6:18)
    at /packages/atom-wannabe/node_modules/wannabe/lib/runner.js:443:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-wannabe/node_modules/wannabe/lib/index.js:10:16)
    at /packages/atom-wannabe/node_modules/wannabe/lib/index.js:154:26)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-wannabe/lib/atom-wannabe.js:7:17)
    at /packages/atom-wannabe/lib/atom-wannabe.js:159:2)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-solarized-dark-syntax 1.2.7 
atom-wannabe 0.4.1 
autoclose-html 0.23.0 
block-comment 0.4.3 
busy-signal 2.0.1 
code-peek 1.4.21 
file-icons 2.1.39 
folded-code-preview 0.2.5 
git-plus 8.7.1 
gl-dark-syntax 3.0.0 
glacier-dark-ui 1.5.0 
ide-typescript 0.9.1 
intentions 1.1.5 
language-docker 1.1.8 
language-graphql 1.0.0 
language-javascript-jsx 0.3.7 
language-jenkinsfile 0.1.1 
lint 0.0.1 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
linter-xo 0.29.0 
minimap 4.29.9 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
pristine-ui 1.1.11 
qolor 0.4.2 
snow-dark-syntax 0.1.1 
sort-lines 0.19.0 
spaces-in-braces 0.1.0 
split-diff 1.6.1 
status-bar-blame 2.0.3 
time-status 1.1.2 
wakatime 9.0.2 
xml-formatter 0.13.0 
```

**Comment by Skywalker13** [comment]
This project is dead because the _debugger API doesn't exists anymore. It was dropped since node v4 IIRC. It must be reworked deeply.

Thanks anyway
